[book]
authors = ["Makise Kurisu"]
language = "en"
multilingual = false
src = "doc"
title = "Single Node Homelab"

[output.html]
git-repository-url = "https://github.com/MakiseKurisu/single-node-homelab/tree/main"
edit-url-template = "https://github.com/MakiseKurisu/single-node-homelab/edit/main/{path}"